packages:
  - packages/*
catalog:
  "@chromatic-com/storybook": ^5.1.2
  "@playwright/test": ^1.59.1
  "@serverlessworkflow/sdk": ^1.0.1
  "@storybook/addon-a11y": ^10.3.5
  "@storybook/addon-docs": ^10.3.5
  "@storybook/addon-vitest": ^10.3.5
  "@storybook/react-vite": ^10.3.5
  "@tailwindcss/vite": ^4.2.2
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.2
  "@testing-library/user-event": ^14.6.1
  "@types/js-yaml": ^4.0.9
  "@types/node": ^25.6.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitest/coverage-v8": ^4.1.5
  "@vitest/ui": ^4.1.5
  "@xyflow/react": ^12.10.2
  husky: ^9.1.7
  "js-yaml": ^4.1.1
  jsdom: ^29.0.2
  lucide-react: ^1.8.0
  lint-staged: ^16.4.0
  oxfmt: ^0.46.0
  oxlint: ^1.61.0
  react: ^19.2.5
  react-dom: ^19.2.5
  rimraf: ^6.1.3
  storybook: ^10.3.5
  syncpack: ^14.3.0
  tailwindcss: ^4.2.2
  typescript: ^6.0.3
  vite: ^8.0.10
  vitest: ^4.1.5
cleanupUnusedCatalogs: true
onlyBuiltDependencies:
  - "@swc/core"
  - chromedriver
  - edgedriver
  - esbuild
  - geckodriver
  - unrs-resolver
