blank_issues_enabled: false
contact_links:
  - name: CNCF Slack (#serverless-workflow)
    url: https://cloud-native.slack.com/archives/CMBAZQSEP
    about: Join our Slack channel for real-time support.